# Generated by Django 5.2 on 2025-05-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_discount_tax_item_currency_order_orderitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
