# Generated by Django 5.2 on 2025-05-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_order_session_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="min_items_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Минимальное количество товаров для применения скидки",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="min_order_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Минимальная сумма заказа для применения скидки",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tax",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[("usd", "USD"), ("eur", "EUR"), ("rub", "RUB")],
                help_text="Налог применяется только для указанной валюты",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tax",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tax",
            name="is_default",
            field=models.BooleanField(default=False, help_text="Налог по умолчанию"),
        ),
    ]
